##服务器配置 生产环境
server:
  port: 8080

project:
  uploadFilePath: /usr/local/tomcat8080/file/
  environment: prod
  wjUrl: http://221.224.13.19:8085/WaterMS/
  url: http://hdxc.weijin365.com/

##数据库durid数据源配置
spring:
  datasource:
      url: jdbc:mysql://114.55.55.28:3306/hdxc?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: hdxc
      password: admin123
      driver-class-name: com.mysql.jdbc.Driver
      platform: mysql
      type: com.alibaba.druid.pool.DruidDataSource
      initialSize: 1
      minIdle: 3
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 30000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      filters: stat,wall,slf4j
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  resources:
    static-locations: classpath:/resources/,classpath:/static/,file:${project.uploadFilePath}
  ### thymeleaf 配置
  thymeleaf:
    cache: false
    check-template-location: true
    servlet:
      content-type: text/html
    enabled: true
    mode: LEGACYHTML5
    prefix: classpath:/templates/
    suffix: .html
  servlet:
      multipart:
        max-file-size: 10Mb
        max-request-size: 100Mb

### mybatis配置
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.vk.model

pagehelper:
  helper-dialect: mysql
  reasonable: false
  support-methods-arguments: true
  params: count=countSql

# 配置logback
#logging:
#  config:  classpath:logback-spring.xml
#
