##服务器配置 开发环境
server:
  port: 8089

project:
#  uploadFilePath: /home/wj/Pictures/Project/
  uploadFilePath: D:/xc/
  environment: dev
#  wjUrl: http://221.224.13.19:8085/WaterMS/
  wjUrl: http://localhost:8080/WaterMS/
  url: http://localhost:8089/

##数据库durid数据源配置
spring:
  datasource:
      url: jdbc:mysql://119.23.128.170:3306/river_inspection?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: fK.3[ocPsM)i-
      driver-class-name: com.mysql.jdbc.Driver
      platform: mysql
      type: com.alibaba.druid.pool.DruidDataSource
      initialSize: 1
      minIdle: 3
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 30000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      filters: stat,wall,slf4j
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  resources:
    static-locations: classpath:/resources/,classpath:/static/,file:${project.uploadFilePath}
  ### thymeleaf 配置
  thymeleaf:
    cache: false
    check-template-location: true
    servlet:
      content-type: text/html
    enabled: true
    mode: LEGACYHTML5
    prefix: classpath:/templates/
    suffix: .html
  servlet:
     multipart:
       max-file-size: 10Mb
       max-request-size: 100Mb

### mybatis配置
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.vk.model

pagehelper:
  helper-dialect: mysql
  reasonable: false
  support-methods-arguments: true
  params: count=countSql


logging:
  level:
    com.vk.mapper: DEBUG

# 配置logback
#logging:
#  config:  classpath:logback-spring.xml
#
